name: ğŸš€ Deploy Backend to EC2

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/backend.yml"
    branches:
      - main

jobs:
  deploy:
    name: ğŸ” Deploy FastAPI to EC2
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Connect to EC2 & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "âœ… ì„œë²„ ì ‘ì† ì„±ê³µ"
            cd ~/nalang_project/server
            git pull origin main
            source venv/bin/activate
            sudo systemctl restart fastapi
            echo "ğŸš€ FastAPI ì„œë²„ ì¬ì‹œì‘ ì™„ë£Œ"
